# Generated by Django 5.2 on 2025-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_name_car_brand_remove_car_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='year',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
